# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '12-Days' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 12-Days
pod "NextLevel"
pod "Alamofire"
end
